# Generated by Django 3.0.8 on 2020-08-17 11:44

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField()),
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=44, size=4)),
                ('length', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_type',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Culture_Genre',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Edu_facility',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('infra_id', models.IntegerField()),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_Genre',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='School_lecture',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wel_facility',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.City')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='Senior_center',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.City')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.City')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Edu_facility')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('target', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('starttime', models.CharField(max_length=10)),
                ('endtime', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.City')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Culture_Genre')),
            ],
        ),
        migrations.AddField(
            model_name='edu_facility',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Infrastructure'),
        ),
        migrations.CreateModel(
            name='Culture_Event',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('target', models.CharField(max_length=15)),
                ('fare', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Culture_Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Course_point',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Course_type'),
        ),
        migrations.CreateModel(
            name='Academy_lecture',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('url', models.URLField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Lecture_Genre')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.City')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Edu_facility')),
            ],
        ),
    ]
