# Generated by Django 3.0.8 on 2020-08-18 05:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='city',
            field=django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=24, size=4),
        ),
    ]
