# Generated by Django 3.0.8 on 2020-08-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200818_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School_lecture',
        ),
    ]
