# Generated by Django 3.0.8 on 2020-08-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20200818_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_center',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
