# Generated by Django 3.0.8 on 2020-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20200818_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_center',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='senior_center',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
