# Generated by Django 3.0.8 on 2020-08-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20200818_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_center',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
