# Generated by Django 3.0.8 on 2020-08-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20200818_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wel_facility',
            name='tel',
        ),
    ]
