# Generated by Django 3.0.8 on 2020-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_remove_wel_facility_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
