# Generated by Django 3.0.8 on 2020-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_auto_20200819_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
