# Generated by Django 3.0.8 on 2020-08-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_auto_20200819_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='academy',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
