# Generated by Django 3.0.8 on 2020-08-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_auto_20200819_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='tel',
            field=models.CharField(max_length=50),
        ),
    ]
