# Generated by Django 3.0.8 on 2020-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_auto_20200819_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_lecture',
            name='level',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academy_lecture',
            name='target',
            field=models.CharField(default='없음', max_length=100),
            preserve_default=False,
        ),
    ]
