# Generated by Django 3.0.8 on 2020-08-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_auto_20200819_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_lecture',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='academy_lecture',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
