# Generated by Django 3.0.8 on 2020-08-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_auto_20200819_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_lecture',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
