# Generated by Django 3.0.8 on 2020-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_auto_20200819_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_point',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course_point',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
