# Generated by Django 3.0.8 on 2020-08-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0024_auto_20200819_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_point',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
