# Generated by Django 3.0.8 on 2020-08-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_auto_20200819_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_event',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Infrastructure'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.Infrastructure'),
        ),
        migrations.DeleteModel(
            name='Cul_facility',
        ),
    ]
