# Generated by Django 3.0.8 on 2020-08-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0026_auto_20200819_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
