# Generated by Django 3.0.8 on 2020-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0030_auto_20200819_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_event',
            name='target',
            field=models.CharField(max_length=50),
        ),
    ]
