# Generated by Django 3.0.8 on 2020-08-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0031_auto_20200819_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_event',
            name='fare',
            field=models.CharField(max_length=200),
        ),
    ]
