# Generated by Django 3.0.8 on 2020-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0034_auto_20200819_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_event',
            name='name',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
