# Generated by Django 3.0.8 on 2020-08-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0035_auto_20200819_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_event',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
