# Generated by Django 3.0.8 on 2020-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0036_auto_20200819_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_event',
            name='fare',
            field=models.CharField(max_length=300),
        ),
    ]
