# Generated by Django 3.0.8 on 2020-08-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0037_auto_20200819_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_genre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='culture_genre',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
