# Generated by Django 3.0.8 on 2020-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0038_auto_20200819_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_genre',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='culture_genre',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
