# Generated by Django 3.0.8 on 2020-08-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0039_auto_20200819_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='city',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='kind',
        ),
        migrations.DeleteModel(
            name='Culture_Event',
        ),
        migrations.DeleteModel(
            name='Culture_Genre',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
    ]
