# Generated by Django 3.0.8 on 2020-08-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0041_culture_event_culture_genre_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_lecture',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academy_lecture',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
