# Generated by Django 3.0.8 on 2020-08-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0044_auto_20200820_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_lecture',
            name='target',
            field=models.CharField(max_length=300),
        ),
    ]
