# Generated by Django 3.0.8 on 2020-08-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0045_auto_20200820_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='city',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='kind',
        ),
        migrations.DeleteModel(
            name='Culture_Event',
        ),
        migrations.DeleteModel(
            name='Culture_genre',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
    ]
